name: Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  publish:
    name: Publish for ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu # x86_64-unknown-linux-musl
            artifact_name: hookbot
            asset_name: hookbot-linux-amd64
          - os: windows-latest
            target: x86_64-pc-windows-msvc
            artifact_name: hookbot.exe
            asset_name: hookbot-windows-amd64.exe
          # - os: macos-latest
          #   artifact_name: hookbot
          #   asset_name: hookbot-macos-amd64

    steps:
      - uses: actions/checkout@v3
      - name: Build
        run: cargo build --release 
      - name: List 
        run: ls -R 
      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: target/release/${{ matrix.artifact_name }}
          asset_name: ${{ matrix.asset_name }}
          tag: ${{ github.ref }}
